import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 *
 *
 * */

// //Office

export const products = [
  {
    _id: uuid(),
    title: "You Can WIN",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "5000",
    categoryName: "office",
    img: "https://i.ibb.co/xCfqp1m/image-6.png",
  },
  {
    _id: uuid(),
    title: "You are Winner",
    author: "Junaid Qures",
    discount: 20,
    qty: 1,
    price: "3000",
    categoryName: "office",
    img: "https://i.ibb.co/y88ptSs/image-7.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/LSFmGqb/image-9.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/1ZcTDxg/image-11.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/kK9J87R/image-14.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/8zSFFYz/image-15.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/jJ3JWLh/image-16.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 30,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/TkFssSw/image-17.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "desk",
    img: "https://i.ibb.co/2W7yS5L/image-18.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 7,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/vYX2gG0/image-19.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/gFT98rc/image-20.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 50,
    qty: 1,
    price: "1000",
    categoryName: "desk",
    img: "https://i.ibb.co/FsX65qy/image-21.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/0yppkv9/image-22.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/m691Nfx/image-23.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "office",
    img: "https://i.ibb.co/C9cLXpc/image-35.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 20,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/4md3grD/image-8.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/1RXnx0w/image-25.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/4Vm762Q/image-26.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 70,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/s2Bgpvt/image-27.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/KxBdJv4/image-28.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/th52sRv/image-29.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/sgtBFbL/image-33.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 70,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/Jj2txqm/image-4.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/k6QgCFT/image-5.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/6HrBGCt/image-10.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/f00jBGD/image-12.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 60,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/bsMQnQK/image-13.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "1000",
    categoryName: "decor",
    img: "https://i.ibb.co/6XhdtfC/image-24.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "4",
    categoryName: "office",
    img: "https://i.ibb.co/zxJkxgj/image-30.png",
  },
  {
    _id: uuid(),
    title: "Think and Grow Rich",
    author: "Shiv Khera",
    discount: 10,
    qty: 1,
    price: "10",
    categoryName: "decor",
    img: "https://i.ibb.co/TcVJK9g/image-31.png",
  },
];
