import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 *
 *
 * */

// //Office

export const products = [
  {
    _id: uuid(),
    title: "LINNMON / ADILS",
    description: "Desk essentio",
    discount: 10,
    qty: 1,
    price: "1299",
    categoryName: "office",
    img: "https://i.ibb.co/xCfqp1m/image-6.png",
  },
  {
    _id: uuid(),
    title: "UNISTH",
    description: "Desk Essential",
    discount: 20,
    qty: 1,
    price: "1299",
    categoryName: "office",
    img: "https://i.ibb.co/y88ptSs/image-7.png",
  },

  {
    _id: uuid(),
    title: "UNISTH",
    description: "Desk Essential",
    discount: 25,
    qty: 1,
    price: "1299",
    categoryName: "office",
    img: "https://i.ibb.co/8zSFFYz/image-15.png",
  },
  {
    _id: uuid(),
    title: "UNISTH",
    description: "Desk Essential",
    discount: 25,
    qty: 1,
    price: "1299",
    categoryName: "office",
    img: "https://i.ibb.co/jJ3JWLh/image-16.png",
  },
  {
    _id: uuid(),
    title: "UNISTH",
    description: "Desk Essential",
    discount: 40,
    qty: 1,
    price: "1299",
    categoryName: "office",
    img: "https://i.ibb.co/LSFmGqb/image-9.png",
  },
  {
    _id: uuid(),
    title: "UNISTH",
    description: "Desk Essential",
    discount: 40,
    qty: 1,
    price: "1299",
    categoryName: "office",
    img: "https://i.ibb.co/1ZcTDxg/image-11.png",
  },
  {
    _id: uuid(),
    title: "UNISTH",
    description: "Desk Essential",
    discount: 40,
    qty: 1,
    price: "1299",
    categoryName: "office",
    img: "https://i.ibb.co/kK9J87R/image-14.png",
  },
  {
    _id: uuid(),
    title: "ALMINO",
    description: "Desk Essential",
    discount: 25,
    qty: 1,
    price: "730",
    categoryName: "office",
    img: "https://i.ibb.co/TkFssSw/image-17.png",
  },
  {
    _id: uuid(),
    title: "ALMINO",
    description: "Desk Essential",
    discount: 80,
    qty: 1,
    price: "730",
    categoryName: "desk",
    img: "https://i.ibb.co/2W7yS5L/image-18.png",
  },

  {
    _id: uuid(),
    title: "BEAGlE",
    description: "Home Leisure",
    discount: 50,
    qty: 1,
    price: "255",
    categoryName: "office",
    img: "https://i.ibb.co/0yppkv9/image-22.png",
  },
  {
    _id: uuid(),
    title: "BEAGlE",
    description: "Home Leisure",
    discount: 50,
    qty: 1,
    price: "399",
    categoryName: "office",
    img: "https://i.ibb.co/m691Nfx/image-23.png",
  },
  {
    _id: uuid(),
    title: "BEAGlE",
    description: "Home Leisure",
    discount: 50,
    qty: 1,
    price: "399",
    categoryName: "office",
    img: "https://i.ibb.co/C9cLXpc/image-35.png",
  },
  {
    _id: uuid(),
    title: "BEAGlE",
    description: "Home Leisure",
    discount: 20,
    qty: 1,
    price: "399",
    categoryName: "decor",
    img: "https://i.ibb.co/4md3grD/image-8.png",
  },
  {
    _id: uuid(),
    title: "BEAGlE",
    description: "Home Leisure",
    discount: 10,
    qty: 1,
    price: "399",
    categoryName: "decor",
    img: "https://i.ibb.co/1RXnx0w/image-25.png",
  },
  {
    _id: uuid(),
    title: "BEAGlE",
    description: "Home Leisure",
    discount: 10,
    qty: 1,
    price: "399",
    categoryName: "decor",
    img: "https://i.ibb.co/4Vm762Q/image-26.png",
  },
  {
    _id: uuid(),
    title: "BEAGlE",
    description: "Home Leisure",
    discount: 70,
    qty: 1,
    price: "5440",
    categoryName: "decor",
    img: "https://i.ibb.co/s2Bgpvt/image-27.png",
  },
  {
    _id: uuid(),
    title: "REGGA",
    description: "Home Leisure",
    discount: 10,
    qty: 1,
    price: "5440",
    categoryName: "decor",
    img: "https://i.ibb.co/KxBdJv4/image-28.png",
  },
  {
    _id: uuid(),
    title: "REGGA",
    description: "Work From Home Productivity",
    discount: 10,
    qty: 1,
    price: "5440",
    categoryName: "decor",
    img: "https://i.ibb.co/th52sRv/image-29.png",
  },
  {
    _id: uuid(),
    title: "ALMINO",
    description: "Desk Essential",
    discount: 80,
    qty: 7,
    price: "730",
    categoryName: "office",
    img: "https://i.ibb.co/vYX2gG0/image-19.png",
  },
  {
    _id: uuid(),
    title: "ALMINO",
    description: "Home Leisure",
    discount: 80,
    qty: 1,
    price: "255",
    categoryName: "office",
    img: "https://i.ibb.co/gFT98rc/image-20.png",
  },
  {
    _id: uuid(),
    title: "ALMINO",
    description: "Home Leisure",
    discount: 50,
    qty: 1,
    price: "255",
    categoryName: "desk",
    img: "https://i.ibb.co/FsX65qy/image-21.png",
  },
  {
    _id: uuid(),
    title: "REGGA",
    description: "Work From Home Productivity",
    discount: 10,
    qty: 1,
    price: "99",
    categoryName: "decor",
    img: "https://i.ibb.co/sgtBFbL/image-33.png",
  },
  {
    _id: uuid(),
    title: "REGGA",
    description: "Work From Home Productivity",
    discount: 70,
    qty: 1,
    price: "99",
    categoryName: "decor",
    img: "https://i.ibb.co/Jj2txqm/image-4.png",
  },
  {
    _id: uuid(),
    title: "REGGA",
    description: "Work From Home Productivity",
    discount: 10,
    qty: 1,
    price: "99",
    categoryName: "decor",
    img: "https://i.ibb.co/k6QgCFT/image-5.png",
  },
  {
    _id: uuid(),
    title: "REGGA",
    description: "Work From Home Productivity",
    discount: 65,
    qty: 1,
    price: "299",
    categoryName: "decor",
    img: "https://i.ibb.co/6HrBGCt/image-10.png",
  },

  {
    _id: uuid(),
    title: "UNIWAS",
    description: "Work From Home Productivity",
    discount: 10,
    qty: 1,
    price: "239",
    categoryName: "office",
    img: "https://i.ibb.co/zxJkxgj/image-30.png",
  },
  {
    _id: uuid(),
    title: "UNIWAS",
    description: "Work From Home Productivity",
    discount: 80,
    qty: 1,
    price: "239",
    categoryName: "decor",
    img: "https://i.ibb.co/TcVJK9g/image-31.png",
  },
  {
    _id: uuid(),
    title: "REGGA",
    description: "Work From Home Productivity",
    discount: 65,
    qty: 1,
    price: "299",
    categoryName: "decor",
    img: "https://i.ibb.co/f00jBGD/image-12.png",
  },
  {
    _id: uuid(),
    title: "REGGA",
    description: "Work From Home Productivity",
    discount: 65,
    qty: 1,
    price: "299",
    categoryName: "decor",
    img: "https://i.ibb.co/bsMQnQK/image-13.png",
  },
  {
    _id: uuid(),
    title: "REGGA",
    description: "Work From Home Productivity",
    discount: 10,
    qty: 1,
    price: "249",
    categoryName: "decor",
    img: "https://i.ibb.co/6XhdtfC/image-24.png",
  },
];
